version: '3.8'
services:
  steam-headless:
    image: my-docker-hub.wz1.570056.xyz:8443/truenas-steam-headless
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 1024
        hard: 524288
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_NICE
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    # NETWORK:
    #network_mode: host
    networks:
      - default
      - web
    hostname: truenas-steam
    extra_hosts:
      - "truenas-steam:127.0.0.1"
    # DEVICES:
    devices:
      # Use the host fuse device.
      - /dev/fuse
      # Add the host uinput device.
      - /dev/uinput
      # Add AMD/Intel HW accelerated video encoding/decoding devices (optional)
      - /dev/nvidia0
      - /dev/nvidiactl
      - /dev/nvidia-uvm
      - /dev/nvidia-uvm-tools
      - /dev/nvidia-modeset
      - /dev/nvidia-caps/nvidia-cap1
      - /dev/nvidia-caps/nvidia-cap2
      
      #- /dev/dri/renderD128
    # Ensure container access to devices 13:*
    device_cgroup_rules:
      - 'c 13:* rmw'
      - 'c 195:* rmw'
      - 'c 240:* rmw'
      - 'c 237:* rmw'

    # VOLUMES:
    volumes:
      #- /var/run/dbus:/run/dbus:ro
      #- /var/run/dbus:/var/run/dbus:ro
      # The location of your home directory.
      - /storage/steam-headless/data:/home/default/:rw

      # The location where all games should be installed.
      # This path needs to be set as a library path in Steam after logging in.
      # Otherwise, Steam will store games in the home directory above.
      #- /home/xe5700/share/games1/:/mnt/games/:rw
      #- /home/xe5700/service/docker-compose/steam-headless/sys/pacman.d:/etc/pacman.d
      # The Xorg socket. This will be shared with other containers so they can access the X server.
      # Select only one option or leave commented out to not share the Xorg socket with any other Docker containers.
      #   Option #1) Start a X server in the container to share with any other containers.
      #- /opt/container-data/steam-headless/.X11-unix/:/tmp/.X11-unix/:rw
      #   Option #2) Use an existing X server running on the host.
      #- /tmp/.X11-unix/:/tmp/.X11-unix/:rw
      #- /tmp/.X11-unix/:/tmp/.X11-unix/:rw
      # - /home/xe5700/service/docker-compose/steam-headless/tmp/:/tmp/
      # Pulse audio socket. This will be shared with other containers so they can access the audio sink.
      # Leave commented out to not share the pulse socket with any other Docker containers.
      #- /opt/container-data/steam-headless/pulse/:/tmp/pulse/:rw


networks:
  web:
    name: proxy_web
    external: true
